dist: bionic
language: c

os:
  - linux

compiler:
  - gcc

addons:
  apt:
    packages:
      - openssl

matrix:
  include:
    - compiler: gcc
      env: BUILD_TYPE=Debug BUILD_TEST=1

    - compiler: gcc
      env: BUILD_TYPE=Release BUILD_TEST=0

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TEST=$BUILD_TEST ..
    - cmake --build ..
    - [[ -n $BUILD_TEST ]] && ctest -V
